### ISSUE TITLE
[FEATURE] Please add example playbook to readme.md

### ISSUE THREAD

**Issue by patsevanton** [idealista/nexus-role#73]
Hello!
Thanks for role nexus!

Please add example playbook to readme.md
Thanks!

**Comment by ablancolopez** [comment]
Hi @patsevanton !

There is already an example playbook at https://github.com/idealista/nexus-role#installing:

```ỳaml
---
- hosts: someserver
  roles:
    - nexus
 ```

**Comment by patsevanton** [comment]
Created PR https://github.com/idealista/nexus-role/pull/74
